"use strict";

const fs = require("fs");
const path = require("path");
const Module = require("module");

const OUTPUT_TAB_WIDTH = 4;
const INPUT_TAB_STOPS = [0, 20, 32, 64];
const LINE_BREAK_PATTERN = /\r\n|\r|\n/;

function retabulate(line) {
	if (line.length === 0) {
		return "";
	}

	let result = "";
	let column = 0;
	let tabIndex = 0;

	const align = (target) => {
		while (column < target) {
			const remainder = column % OUTPUT_TAB_WIDTH;
			const next = column + (remainder === 0 ? OUTPUT_TAB_WIDTH : OUTPUT_TAB_WIDTH - remainder);
			if (next > target) {
				break;
			}
			result += "\t";
			column = next;
		}
		if (column < target) {
			result += " ".repeat(target - column);
			column = target;
		}
	};

	for (const segment of line.split("\t")) {
		const stop = INPUT_TAB_STOPS[tabIndex] ?? -Infinity;
		align(Math.max(stop, column + 1));
		tabIndex += 1;
		result += segment;
		column += segment.length;
	}

	return result;
}

function clampIndex(value, min, max) {
	return Number.isFinite(value) ? Math.min(Math.max(Math.floor(value), min), max) : min;
}

function getLineInfo(source, rawIndex) {
	const index = clampIndex(rawIndex, 0, source.length);
	const head = source.slice(0, index);
	const segments = head.split(LINE_BREAK_PATTERN);
	const last = segments[segments.length - 1] ?? "";
	const lineStart = index - last.length;
	const match = source.slice(index).match(LINE_BREAK_PATTERN);
	const lineEnd = match ? index + match.index : source.length;
	return {
		index,
		line: segments.length,
		lineStart,
		lineEnd,
		lineText: source.slice(lineStart, lineEnd),
	};
}

function renderErrorContext(lineText, pointerOffset) {
	let displayLine = "";
	let pointerColumn = 0;
	let column = 0;

	for (let i = 0; i < lineText.length; i += 1) {
		const ch = lineText[i];
		if (ch === "\t") {
			const spaces = ((column + OUTPUT_TAB_WIDTH) & ~(OUTPUT_TAB_WIDTH - 1)) - column;
			displayLine += " ".repeat(spaces);
			if (i < pointerOffset) {
				pointerColumn += spaces;
			}
			column += spaces;
			continue;
		}
		const code = ch.charCodeAt(0);
		displayLine += code >= 0x20 && code !== 0x7f ? ch : " ";
		if (i < pointerOffset) {
			pointerColumn += 1;
		}
		column += 1;
	}

	if (pointerOffset >= lineText.length) {
		pointerColumn = column;
	}

	return {
		displayLine,
		pointerLine: `${" ".repeat(pointerColumn)}^`,
		column: pointerColumn + 1,
	};
}

function formatErrorWithLocation(source, options, rawIndex, baseMessage, explicitLocationLabel) {
	const { index, line, lineStart, lineEnd, lineText } = getLineInfo(source, rawIndex);
	const context = renderErrorContext(lineText, index - lineStart);
	const locationLabel = explicitLocationLabel ?? (options && options.sourceName ? ` ${options.sourceName}` : " source");
	const detail = context.displayLine.length > 0 || lineEnd > lineStart ? `\n${context.displayLine}\n${context.pointerLine}` : "\n^";
	return `${baseMessage}${locationLabel} at line ${line}, column ${context.column}, offset ${index}.${detail}`;
}

function formatThrownCompilerError(err, source, options) {
	if (err && typeof err === "object" && Number.isFinite(err.impalaOffset)) {
		const baseMessage = err.impalaMessage || (err.message ? err.message.split(" : ")[0] : "JSPEG impala compiler error");
		return formatErrorWithLocation(source, options, err.impalaOffset, baseMessage);
	}
	if (err && err.message) {
		return err.message;
	}
	return String(err);
}

//
// NOTE: The Impala compiler bundle under `impalaCompiler.js` is generated by the
// upstream JSPEG toolchain. Build-time hardening injects the safety helpers when
// regenerating the bundle, so the runner simply loads the emitted source verbatim.
//

function resolveCompilerExport(candidate) {
	if (typeof candidate === "function") {
		return candidate;
	}
	if (candidate && typeof candidate === "object") {
		return candidate.impalaCompiler || candidate.default || candidate.compile || candidate.compiler || candidate;
	}
	return undefined;
}

function loadCompilerModule(compilerSource, compilerFilename) {
	const compilerModule = new Module(compilerFilename, module);
	compilerModule.filename = compilerFilename;
	compilerModule.paths = Module._nodeModulePaths(path.dirname(compilerFilename));
	compilerModule.require = Module.createRequire(compilerFilename);
	compilerModule._compile(compilerSource, compilerFilename);
	return compilerModule.exports;
}

function compileWithJsImpala(source, options = {}) {
	const {
		compilerPath: compilerPathOption,
		compilerSource,
		sourceName,
		retabulate: shouldRetabulate = true,
		trailingNewline,
		randomId,
	} = options;

	const compilerPath = compilerPathOption ? path.resolve(compilerPathOption) : path.join(__dirname, "impalaCompiler.js");
	const compilerText = compilerSource ?? fs.readFileSync(compilerPath, "utf8");

	const outputLines = [];
	const compilerExports = loadCompilerModule(compilerText, compilerPath);
	const compilerFn = resolveCompilerExport(compilerExports);
	if (typeof compilerFn !== "function") {
		throw new Error("JSPEG impala compiler did not export a function");
	}

	const compilerOptions = {
		output: (line) => outputLines.push(line),
	};
	if (randomId !== undefined) {
		compilerOptions.randomId = randomId;
	}
	if (sourceName !== undefined) {
		compilerOptions.sourceName = sourceName;
	}
	let compileResult;
	try {
		compileResult = compilerFn(source, compilerOptions);
	} catch (err) {
		throw new Error(formatThrownCompilerError(err, source, options));
	}
	const [ok, , index] = compileResult;
	if (!ok) {
		throw new Error(formatErrorWithLocation(source, options, index, "JSPEG impala compiler failed to compile"));
	}
	if (index !== source.length) {
		throw new Error(`JSPEG impala compiler stopped at ${index} of ${source.length}`);
	}

	if (outputLines.length === 0) {
		return "";
	}

	const formatted = shouldRetabulate ? outputLines.map(retabulate) : outputLines;
	let outputText = formatted.join("\n");

	if (trailingNewline === true || (trailingNewline === undefined && shouldRetabulate)) {
		outputText += "\n";
	} else if (!shouldRetabulate && trailingNewline !== true) {
		while (outputText.endsWith("\n")) {
			outputText = outputText.slice(0, -1);
		}
	}

	return outputText;
}

module.exports = {
	compileWithJsImpala,
};
