/* GENERATED from impala/jspeg.jspeg by `node impala/updateJSPEG.js` -- do not edit by hand. */
var compileJSPEG = (function(_s) {
{
        function dqEscape(s) {
                return JSON.stringify(s);
        }

        function hasOwn(obj, key) {
                return Object.prototype.hasOwnProperty.call(obj, key);
        }

        function classRangeError(s, i) {
                var line = 1, col = 1;
                for (var k = 0; k < i - 1; ++k) {
                        if (s.charCodeAt(k) === 10) { ++line; col = 1; } else { ++col; }
                }
                throw new Error("character class at line " + line + ":" + col
                        + ": '-' before ']' makes a range ending at the class terminator."
                        + " Escape it as \\] for a real range to ']', or put '-' first for a literal dash");
        }

        // The current rule's variable map. It used to be threaded down through holders
        // (`$$.vr`); with value-returning rules there is no holder to carry it, and rules never
        // nest, so one global set by `Definition` is exactly equivalent.
        var _vr = null;

};function root(){var $fn,$b,$g={},_sv$g;return (function(){var _b=_i;return (function(){ $fn = "(function(_s) {\n"; ; return true})()&&((function(){var _b=_i;return Spacing()&&(function(){var _m=_i;return PikaBlock()&&($b=_s.slice(_m,_i),true)})()&&(function(){ $fn += $b.replace(/\x24\x24parser\./g, '') + ';' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})(),true)&&Spacing()&&((_sv$g=_val,_val=$g,(Grammar()))&&($g=_val,_val=_sv$g,true)||(_val=_sv$g,false))&&(function(){ $fn += $g; $fn += "var _i=0,_im=0,_val,_b=root();\n"; $fn += "return [_b,_val,(_b?_i:_im)];\n})\n"; _val = $fn; ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Grammar(){var $d={},_sv$d;return (function(){var _b=_i;return (function(){ _val = '' ; return true})()&&Spacing()&&((function(){while((function(){var _b=_i;return ((_sv$d=_val,_val=$d,(Definition()))&&($d=_val,_val=_sv$d,true)||(_val=_sv$d,false))&&(function(){ _val += $d + ";\n" ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&EndOfFile()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Definition(){var $id={},_sv$id,$e={},_sv$e;return (function(){var _b=_i;return ((_sv$id=_val,_val=$id,(Identifier()))&&($id=_val,_val=_sv$id,true)||(_val=_sv$id,false))&&LEFTARROW()&&(function(){ _vr = {}; ; return true})()&&((_sv$e=_val,_val=$e,(Expression()))&&($e=_val,_val=_sv$e,true)||(_val=_sv$e,false))&&(function(){ var _vl = ''; for (var _k in _vr) { if (hasOwn(_vr, _k)) { _vl += (_vl !== '' ? ',' : '') + _k + _vr[_k]; } } _val = 'function ' + $id + '(){' + (_vl === '' ? '' : ('var ' + _vl + ';')) + 'return ' + $e + '}' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Expression(){var $s={},_sv$s;return (function(){var _b=_i;return Sequence()&&((function(){while((function(){var _b=_i;return SLASH()&&((_sv$s=_val,_val=$s,(Sequence()))&&($s=_val,_val=_sv$s,true)||(_val=_sv$s,false))&&(function(){ _val += '||' + $s ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(function(){ _val = '(function(){var _b=_i;return ' + _val + '})()' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Sequence(){var $p={},_sv$p;return (function(){var _b=_i;return (function(){ _val = '' ; return true})()&&((function(){while((function(){var _b=_i;return ((_sv$p=_val,_val=$p,((function(){var _b=_i;return Prefix()||(_im=(_i>_im?_i:_im),_i=_b,false)||Action()||(_im=(_i>_im?_i:_im),_i=_b,false)})()))&&($p=_val,_val=_sv$p,true)||(_val=_sv$p,false))&&(function(){ _val += (_val !== '' ? '&&' : '') + $p ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(function(){ _val += (_val === '' ? 'true' : '||(_im=(_i>_im?_i:_im),_i=_b,false)') ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Action(){var $b,$;return (function(){var _b=_i;return (function(){var _m=_i;return PikaBlock()&&($b=_s.slice(_m,_i),true)})()&&Spacing()&&(function(){ $b = $b.slice(1, $b.length - 1); for (var s = '(function(){'; $b.length > 0; ) { // find first of $,/,tab,CR,LF
                                                                                                  var idx = $b.search(/[$/\t\r\n]/); var cut = (idx === -1 ? $b.length : idx); s += $b.slice(0, cut); $b = $b.slice(cut); if ($b.length === 0) { continue; } if ($b[0] === '$') { if ($b.slice(0, 9) === '\x24\x24parser.') { $b = $b.slice(9); } else if ($b.slice(0, 3) === '\x24\x24s') { s += '_s'; $b = $b.slice(3); } else if ($b.slice(0, 3) === '\x24\x24i') { s += '_i'; $b = $b.slice(3); } else if ($b.slice(0, 2) === '\x24\x24') { s += '_val'; $b = $b.slice(2); } else { var m = $b.slice(1).match(/^[A-Za-z_]+/); var e = (m ? m[0].length : 0) + 1; var id = $b.slice(0, e); s += id; $b = $b.slice(e); if (!hasOwn(_vr, id)) { _vr[id] = ''; } } } else if ($b.slice(0, 2) === '//') {
                                                                                                    var newline = $b.indexOf('\n'); var span = (newline === -1 ? $b.length : newline + 1); s += $b.slice(0, span); $b = $b.slice(span); } else if ($b[0] === '/') { s += '/'; $b = $b.slice(1); } else { if (s[s.length - 1] !== ' ') s += ' '; var ws = $b.match(/^[ \t\r\n]+/); $b = $b.slice(ws ? ws[0].length : 0); } } _val = s + '; return true})()'; ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Prefix(){var $c={},_sv$c;return (function(){var _b=_i;return AND()&&((_sv$c=_val,_val=$c,(Capture()))&&($c=_val,_val=_sv$c,true)||(_val=_sv$c,false))&&(function(){ _val = '(function(){var _l=_i,_lv=_val' + ',_x=' + $c + ';_i=_l;_val=_lv;return _x})()' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||NOT()&&((_sv$c=_val,_val=$c,(Capture()))&&($c=_val,_val=_sv$c,true)||(_val=_sv$c,false))&&(function(){ _val = '(function(){var _l=_i,_lv=_val' + ',_x=' + $c + ';_i=_l;_val=_lv;return !_x})()' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||Capture()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Capture(){var $v={},_sv$v,$t={},_sv$t;return (function(){var _b=_i;return ((_sv$v=_val,_val=$v,(Variable()))&&($v=_val,_val=_sv$v,true)||(_val=_sv$v,false))&&EQUALS()&&(function(){ if ($v !== '_val') _vr[$v] = '' ; return true})()&&((_sv$t=_val,_val=$t,(Tagged()))&&($t=_val,_val=_sv$t,true)||(_val=_sv$t,false))&&(function(){ _val = '(function(){var _m=_i;return ' + $t + '&&(' + $v + '=_s.slice(_m,_i),true)})()' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||Tagged()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Tagged(){var $v={},_sv$v,$t={},_sv$t;return (function(){var _b=_i;return ((_sv$v=_val,_val=$v,(Variable()))&&($v=_val,_val=_sv$v,true)||(_val=_sv$v,false))&&COLON()&&(function(){ if ($v !== '_val') { _vr[$v] = '={}'; _vr['_sv' + $v] = '' } ; return true})()&&((_sv$t=_val,_val=$t,(Suffix()))&&($t=_val,_val=_sv$t,true)||(_val=_sv$t,false))&&(function(){ if ($v === '_val') _val = $t; else { var _q = '_sv' + $v; _val = '((' + _q + '=_val,_val=' + $v + ',(' + $t + '))&&(' + $v + '=_val,_val=' + _q + ',true)||(_val=' + _q + ',false))' } ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||Suffix()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Suffix(){return (function(){var _b=_i;return Primary()&&((function(){var _b=_i;return QUESTION()&&(function(){ _val = '(' + _val + ',true)' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||STAR()&&(function(){ _val = '((function(){while(' + _val + ');})(),true)' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||PLUS()&&(function(){ _val = '((function(){for(var _n=0;' + _val + ';++_n);return _n>0})())' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})(),true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Primary(){var $id={},_sv$id,$l={},_sv$l,$c={},_sv$c;return (function(){var _b=_i;return ((_sv$id=_val,_val=$id,(Identifier()))&&($id=_val,_val=_sv$id,true)||(_val=_sv$id,false))&&(function(){var _l=_i,_lv=_val,_x=LEFTARROW();_i=_l;_val=_lv;return !_x})()&&(function(){ _val = $id + '()' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||((_sv$l=_val,_val=$l,(Literal()))&&($l=_val,_val=_sv$l,true)||(_val=_sv$l,false))&&(function(){ var n = ($l).length; if (n == 0) _val = 'true'; else if (n == 1) _val = '(_s[_i]===' + dqEscape($l) + ')&&(++_i,true)'; else _val = '(_s.substr(_i,' + n + ')===' + dqEscape($l) + ')&&(_i+=' + n + ',true)'; ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||((_sv$c=_val,_val=$c,(Class()))&&($c=_val,_val=_sv$c,true)||(_val=_sv$c,false))&&(function(){ _val = '(!!_s[_i]&&' + dqEscape($c) + '.indexOf(_s[_i])>=0)&&(++_i,true)' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||DOT()&&(function(){ _val = '(!!_s[_i])&&(++_i,true)' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||OPEN()&&Expression()&&CLOSE()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Identifier(){return (function(){var _b=_i;return (function(){var _m=_i;return (function(){var _b=_i;return IdentStart()&&((function(){while(IdentCont());})(),true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()&&(_val=_s.slice(_m,_i),true)})()&&Spacing()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function IdentStart(){return (function(){var _b=_i;return (!!_s[_i]&&"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_".indexOf(_s[_i])>=0)&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function IdentCont(){return (function(){var _b=_i;return IdentStart()||(_im=(_i>_im?_i:_im),_i=_b,false)||(!!_s[_i]&&"0123456789".indexOf(_s[_i])>=0)&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Variable(){var $;return (function(){var _b=_i;return (function(){var _b=_i;return (_s.substr(_i,2)==="$$")&&(_i+=2,true)&&(function(){ _val = '_val' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||(function(){var _m=_i;return PikaVar()&&(_val=_s.slice(_m,_i),true)})()&&(function(){ _val = '$' + _val ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()&&Spacing()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Literal(){var $c={},_sv$c;return (function(){var _b=_i;return (function(){ _val = '' ; return true})()&&(!!_s[_i]&&"'".indexOf(_s[_i])>=0)&&(++_i,true)&&((function(){while((function(){var _b=_i;return (function(){var _l=_i,_lv=_val,_x=(!!_s[_i]&&"'".indexOf(_s[_i])>=0)&&(++_i,true);_i=_l;_val=_lv;return !_x})()&&((_sv$c=_val,_val=$c,(Char()))&&($c=_val,_val=_sv$c,true)||(_val=_sv$c,false))&&(function(){ _val += $c ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(!!_s[_i]&&"'".indexOf(_s[_i])>=0)&&(++_i,true)&&Spacing()||(_im=(_i>_im?_i:_im),_i=_b,false)||(!!_s[_i]&&"\"".indexOf(_s[_i])>=0)&&(++_i,true)&&((function(){while((function(){var _b=_i;return (function(){var _l=_i,_lv=_val,_x=(!!_s[_i]&&"\"".indexOf(_s[_i])>=0)&&(++_i,true);_i=_l;_val=_lv;return !_x})()&&((_sv$c=_val,_val=$c,(Char()))&&($c=_val,_val=_sv$c,true)||(_val=_sv$c,false))&&(function(){ _val += $c ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(!!_s[_i]&&"\"".indexOf(_s[_i])>=0)&&(++_i,true)&&Spacing()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Class(){var $r={},_sv$r;return (function(){var _b=_i;return (function(){ _val = '' ; return true})()&&(_s[_i]==="[")&&(++_i,true)&&((function(){while((function(){var _b=_i;return (function(){var _l=_i,_lv=_val,_x=(_s[_i]==="]")&&(++_i,true);_i=_l;_val=_lv;return !_x})()&&((_sv$r=_val,_val=$r,(Range()))&&($r=_val,_val=_sv$r,true)||(_val=_sv$r,false))&&(function(){ _val += $r ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(_s[_i]==="]")&&(++_i,true)&&Spacing()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Range(){var $f={},_sv$f,$t={},_sv$t;return (function(){var _b=_i;return Char()&&(_s[_i]==="-")&&(++_i,true)&&(function(){var _l=_i,_lv=_val,_x=(_s[_i]==="]")&&(++_i,true);_i=_l;_val=_lv;return _x})()&&(function(){ classRangeError(_s, _i) ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||((_sv$f=_val,_val=$f,(Char()))&&($f=_val,_val=_sv$f,true)||(_val=_sv$f,false))&&(_s[_i]==="-")&&(++_i,true)&&((_sv$t=_val,_val=$t,(Char()))&&($t=_val,_val=_sv$t,true)||(_val=_sv$t,false))&&(function(){ _val = ''; for (var i = ($f).charCodeAt(0), e = ($t).charCodeAt(0); i <= e; ++i) _val += String.fromCharCode(i); ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||Char()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Char(){var $x;return (function(){var _b=_i;return (_s[_i]==="\\")&&(++_i,true)&&(function(){var _m=_i;return (!!_s[_i]&&"nrt'\"[]\\".indexOf(_s[_i])>=0)&&(++_i,true)&&($x=_s.slice(_m,_i),true)})()&&(function(){ _val = "\n\r\t'\"[]\\"[("nrt'\"[]\\").indexOf($x)] ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||(_s[_i]==="\\")&&(++_i,true)&&(function(){var _m=_i;return (function(){var _b=_i;return (!!_s[_i]&&"0123".indexOf(_s[_i])>=0)&&(++_i,true)&&(!!_s[_i]&&"01234567".indexOf(_s[_i])>=0)&&(++_i,true)&&(!!_s[_i]&&"01234567".indexOf(_s[_i])>=0)&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()&&($x=_s.slice(_m,_i),true)})()&&(function(){ _val = String.fromCharCode($x[0] * 64 + $x[1] * 8 + +$x[2]) ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||(_s[_i]==="\\")&&(++_i,true)&&(function(){var _m=_i;return (function(){var _b=_i;return (!!_s[_i]&&"01234567".indexOf(_s[_i])>=0)&&(++_i,true)&&(!!_s[_i]&&"01234567".indexOf(_s[_i])>=0)&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()&&($x=_s.slice(_m,_i),true)})()&&(function(){ _val = String.fromCharCode($x[0] * 8 + +$x[1]) ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||(_s[_i]==="\\")&&(++_i,true)&&(function(){var _m=_i;return (function(){var _b=_i;return (!!_s[_i]&&"01234567".indexOf(_s[_i])>=0)&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()&&($x=_s.slice(_m,_i),true)})()&&(function(){ _val = String.fromCharCode(+$x[0]) ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||(function(){var _l=_i,_lv=_val,_x=(!!_s[_i]&&"\\\u0000\u0001\u0002\u0003\u0004\u0005\u0006\u0007\b\t\n\u000b\f\r\u000e\u000f\u0010\u0011\u0012\u0013\u0014\u0015\u0016\u0017\u0018\u0019\u001a\u001b\u001c\u001d\u001e\u001f".indexOf(_s[_i])>=0)&&(++_i,true);_i=_l;_val=_lv;return !_x})()&&(function(){var _m=_i;return (!!_s[_i])&&(++_i,true)&&(_val=_s.slice(_m,_i),true)})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Spacing(){return (function(){var _b=_i;return ((function(){while((function(){var _b=_i;return Space()||(_im=(_i>_im?_i:_im),_i=_b,false)||Comment()||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Comment(){return (function(){var _b=_i;return (_s[_i]==="#")&&(++_i,true)&&((function(){while((function(){var _b=_i;return (function(){var _l=_i,_lv=_val,_x=EndOfLine();_i=_l;_val=_lv;return !_x})()&&(!!_s[_i])&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(function(){var _b=_i;return EndOfLine()||(_im=(_i>_im?_i:_im),_i=_b,false)||EndOfFile()||(_im=(_i>_im?_i:_im),_i=_b,false)})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Space(){return (function(){var _b=_i;return (_s[_i]===" ")&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)||(_s[_i]==="\t")&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)||EndOfLine()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function EndOfLine(){return (function(){var _b=_i;return (_s.substr(_i,2)==="\r\n")&&(_i+=2,true)||(_im=(_i>_im?_i:_im),_i=_b,false)||(_s[_i]==="\n")&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)||(_s[_i]==="\r")&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function EndOfFile(){return (function(){var _b=_i;return (function(){var _l=_i,_lv=_val,_x=(!!_s[_i])&&(++_i,true);_i=_l;_val=_lv;return !_x})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function PikaVar(){return (function(){var _b=_i;return (!!_s[_i]&&"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_".indexOf(_s[_i])>=0)&&(++_i,true)&&((function(){while((!!_s[_i]&&"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ$_0123456789".indexOf(_s[_i])>=0)&&(++_i,true));})(),true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function PikaBlock(){return (function(){var _b=_i;return (_s[_i]==="{")&&(++_i,true)&&((function(){while((function(){var _b=_i;return (function(){var _l=_i,_lv=_val,_x=(_s[_i]==="{")&&(++_i,true);_i=_l;_val=_lv;return _x})()&&PikaBlock()||(_im=(_i>_im?_i:_im),_i=_b,false)||(function(){var _l=_i,_lv=_val,_x=(!!_s[_i]&&"\"'".indexOf(_s[_i])>=0)&&(++_i,true);_i=_l;_val=_lv;return _x})()&&PikaString()||(_im=(_i>_im?_i:_im),_i=_b,false)||(function(){var _l=_i,_lv=_val,_x=(function(){var _b=_i;return (_s.substr(_i,2)==="/*")&&(_i+=2,true)||(_im=(_i>_im?_i:_im),_i=_b,false)||(_s.substr(_i,2)==="//")&&(_i+=2,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})();_i=_l;_val=_lv;return _x})()&&PikaComment()||(_im=(_i>_im?_i:_im),_i=_b,false)||(function(){var _l=_i,_lv=_val,_x=(_s[_i]==="}")&&(++_i,true);_i=_l;_val=_lv;return !_x})()&&(!!_s[_i])&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(_s[_i]==="}")&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function PikaString(){return (function(){var _b=_i;return (_s[_i]==="\"")&&(++_i,true)&&((function(){while((function(){var _b=_i;return (function(){var _b=_i;return (_s[_i]==="\\")&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)||(function(){var _l=_i,_lv=_val,_x=(_s[_i]==="\"")&&(++_i,true);_i=_l;_val=_lv;return !_x})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()&&(!!_s[_i])&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(_s[_i]==="\"")&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)||(_s[_i]==="'")&&(++_i,true)&&((function(){while((function(){var _b=_i;return (function(){var _b=_i;return (_s.substr(_i,2)==="''")&&(_i+=2,true)||(_im=(_i>_im?_i:_im),_i=_b,false)||(function(){var _l=_i,_lv=_val,_x=(_s[_i]==="'")&&(++_i,true);_i=_l;_val=_lv;return !_x})()&&(!!_s[_i])&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(_s[_i]==="'")&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function PikaComment(){return (function(){var _b=_i;return (_s.substr(_i,2)==="/*")&&(_i+=2,true)&&((function(){while((function(){var _b=_i;return (function(){var _l=_i,_lv=_val,_x=(_s.substr(_i,2)==="*/")&&(_i+=2,true);_i=_l;_val=_lv;return !_x})()&&(!!_s[_i])&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(_s.substr(_i,2)==="*/")&&(_i+=2,true)||(_im=(_i>_im?_i:_im),_i=_b,false)||(_s.substr(_i,2)==="//")&&(_i+=2,true)&&((function(){while((function(){var _b=_i;return (function(){var _l=_i,_lv=_val,_x=EndOfLine();_i=_l;_val=_lv;return !_x})()&&(!!_s[_i])&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(function(){var _b=_i;return EndOfLine()||(_im=(_i>_im?_i:_im),_i=_b,false)||EndOfFile()||(_im=(_i>_im?_i:_im),_i=_b,false)})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function LEFTARROW(){return (function(){var _b=_i;return (_s.substr(_i,2)==="<-")&&(_i+=2,true)&&Spacing()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function SLASH(){return (function(){var _b=_i;return (_s[_i]==="/")&&(++_i,true)&&Spacing()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function AND(){return (function(){var _b=_i;return (_s[_i]==="&")&&(++_i,true)&&Spacing()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function NOT(){return (function(){var _b=_i;return (_s[_i]==="!")&&(++_i,true)&&Spacing()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function QUESTION(){return (function(){var _b=_i;return (_s[_i]==="?")&&(++_i,true)&&Spacing()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function STAR(){return (function(){var _b=_i;return (_s[_i]==="*")&&(++_i,true)&&Spacing()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function PLUS(){return (function(){var _b=_i;return (_s[_i]==="+")&&(++_i,true)&&Spacing()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function OPEN(){return (function(){var _b=_i;return (_s[_i]==="(")&&(++_i,true)&&Spacing()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function CLOSE(){return (function(){var _b=_i;return (_s[_i]===")")&&(++_i,true)&&Spacing()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function DOT(){return (function(){var _b=_i;return (_s[_i]===".")&&(++_i,true)&&Spacing()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function COLON(){return (function(){var _b=_i;return (_s[_i]===":")&&(++_i,true)&&Spacing()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function EQUALS(){return (function(){var _b=_i;return (_s[_i]==="=")&&(++_i,true)&&Spacing()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
var _i=0,_im=0,_val,_b=root();
return [_b,_val,(_b?_i:_im)];
});
if (typeof module !== 'undefined' && module.exports) {
	module.exports = compileJSPEG;
	module.exports.compileJSPEG = compileJSPEG;
	module.exports.default = compileJSPEG;
}
