var compileJSPEG = (function(_s) {
{
        function dqEscape(s) {
                return JSON.stringify(s);
        }

        function hasOwn(obj, key) {
                return Object.prototype.hasOwnProperty.call(obj, key);
        }
};function root($){var $fn,$b,$g={};return (function(){var _b=_i;return (function(){ $fn = "(function(_s) {\n"; ; return true})()&&((function(){var _b=_i;return Spacing($)&&(function(){var _m=_i;return PikaBlock($)&&($b=_s.slice(_m,_i),true)})()&&(function(){ $fn += $b.replace(/\x24\x24parser\./g, '') + ';' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})(),true)&&Spacing($)&&Grammar($g)&&(function(){ $fn += $g._; $fn += "var _i=0,_im=0,_o={_:void 0},_b=root(_o);\n"; $fn += "return [_b,_o._,(_b?_i:_im)];\n})\n"; $._ = $fn; ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Grammar($){var $d={};return (function(){var _b=_i;return (function(){ $._ = '' ; return true})()&&Spacing($)&&((function(){while((function(){var _b=_i;return Definition($d)&&(function(){ $._ += $d._ + ";\n" ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&EndOfFile($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Definition($){var $id={},$,$vars;return (function(){var _b=_i;return Identifier($id)&&LEFTARROW($)&&(function(){ $.tag = '$'; $.vi = 0; $.vr = $vars = {} ; return true})()&&Expression($)&&(function(){ var _v = ''; var _p = ''; for (var _k in $vars) { if (hasOwn($vars, _k)) { if (_k.indexOf('.') !== -1) { if ($vars[_k] !== '') { _p += _k + $vars[_k] + ';'; } } else { _v += (_v !== '' ? ',' : '') + _k + $vars[_k]; } } } $._ = 'function ' + $id._ + '($){' + (_v === '' ? '' : ('var ' + _v + ';')) + _p + 'return ' + $._ + '}' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Expression($){var $s={};return (function(){var _b=_i;return (function(){ $s.vi = $.vi + 1; $s.tag = $.tag; $s.vr = $.vr; $._ = '' ; return true})()&&Sequence($s)&&(function(){ $._ = $s._ ; return true})()&&((function(){while((function(){var _b=_i;return SLASH($)&&Sequence($s)&&(function(){ $._ += '||' + $s._ ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(function(){ $._ = '(function(){var _b=_i;return ' + $._ + '})()' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Sequence($){var $p={};return (function(){var _b=_i;return (function(){ $p.vi = $.vi; $p.tag = $.tag; $p.vr = $.vr; $._ = '' ; return true})()&&((function(){while((function(){var _b=_i;return (function(){var _b=_i;return Prefix($p)||(_im=(_i>_im?_i:_im),_i=_b,false)||Action($p)||(_im=(_i>_im?_i:_im),_i=_b,false)})()&&(function(){ $._ += ($._ !== '' ? '&&' : '') + $p._ ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(function(){ $._ += ($._ === '' ? 'true' : '||(_im=(_i>_im?_i:_im),_i=_b,false)') ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Action($){var $b,$;return (function(){var _b=_i;return (function(){var _m=_i;return PikaBlock($)&&($b=_s.slice(_m,_i),true)})()&&Spacing($)&&(function(){ $b = $b.slice(1, $b.length - 1); for (var s = '(function(){'; $b.length > 0; ) { // find first of $,/,tab,CR,LF
                                                                                                  var idx = $b.search(/[$/\t\r\n]/); var cut = (idx === -1 ? $b.length : idx); s += $b.slice(0, cut); $b = $b.slice(cut); if ($b.length === 0) { continue; } if ($b[0] === '$') { if ($b.slice(0, 9) === '\x24\x24parser.') { $b = $b.slice(9); } else if ($b.slice(0, 3) === '\x24\x24s') { s += '_s'; $b = $b.slice(3); } else if ($b.slice(0, 3) === '\x24\x24i') { s += '_i'; $b = $b.slice(3); } else if ($b.slice(0, 3) === '\x24\x24.') { var next = $b[3] || ''; var keepDot = /[A-Za-z0-9_$]/.test(next); s += '$'; if (keepDot) { s += '.'; } $b = $b.slice(3); } else if ($b.slice(0, 2) === '\x24\x24') { s += '$._'; $b = $b.slice(2); } else { var m = $b.slice(1).match(/^[A-Za-z_]+/); var e = (m ? m[0].length : 0) + 1; var id = $b.slice(0, e); s += id; $b = $b.slice(e); if (!hasOwn($.vr, id)) { $.vr[id] = ''; } else if ($.vr[id] !== '' && $b[0] !== '.') { s += '._'; } } } else if ($b.slice(0, 2) === '//') {
                                                                                                    var newline = $b.indexOf('\n'); var span = (newline === -1 ? $b.length : newline + 1); s += $b.slice(0, span); $b = $b.slice(span); } else if ($b[0] === '/') { s += '/'; $b = $b.slice(1); } else { if (s[s.length - 1] !== ' ') s += ' '; var ws = $b.match(/^[ \t\r\n]+/); $b = $b.slice(ws ? ws[0].length : 0); } } $._ = s + '; return true})()'; ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Prefix($){var $c={};return (function(){var _b=_i;return (function(){ $c.vi = $.vi; $c.tag = $.tag; $c.vr = $.vr ; return true})()&&AND($)&&Capture($c)&&(function(){ $._ = '(function(){var _l=_i' + ',_x=' + $c._ + ';_i=_l;return _x})()' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||NOT($)&&Capture($c)&&(function(){ $._ = '(function(){var _l=_i' + ',_x=' + $c._ + ';_i=_l;return !_x})()' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||Capture($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Capture($){var $v={},$;return (function(){var _b=_i;return Variable($v)&&EQUALS($)&&(function(){ if ($v._ !== '$._') $.vr[$v._] = ''; ; return true})()&&Tagged($)&&(function(){ $._ = '(function(){var _m=_i;return ' + $._ + '&&(' + $v._ + '=_s.slice(_m,_i),true)})()' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||Tagged($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Tagged($){var $v={},$t={},$;return (function(){var _b=_i;return Variable($v)&&COLON($)&&(function(){ $t.vi = $.vi; if ($v._ !== '$._') { $t.tag = $v._; ($t.vr = $.vr)[$v._] = '={}' } else $t.tag = '$' ; return true})()&&Suffix($t)&&(function(){ $._ = $t._ ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||Suffix($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Suffix($){return (function(){var _b=_i;return Primary($)&&((function(){var _b=_i;return QUESTION($)&&(function(){ $._ = '(' + $._ + ',true)' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||STAR($)&&(function(){ $._ = '((function(){while(' + $._ + ');})(),true)' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||PLUS($)&&(function(){ $._ = '((function(){for(var _n=0;' + $._ + ';++_n);return _n>0})())' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})(),true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Primary($){return (function(){var _b=_i;return Identifier($)&&(function(){var _l=_i,_x=LEFTARROW($);_i=_l;return !_x})()&&(function(){ $._ += '(' + $.tag + ')' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||Literal($)&&(function(){ var l = ($._).length; if (l == 0) $._ = 'true'; else if (l == 1) $._ = '(_s[_i]===' + dqEscape($._) + ')&&(++_i,true)'; else $._ = '(_s.substr(_i,' + l + ')===' + dqEscape($._) + ')&&(_i+=' + l + ',true)'; ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||Class($)&&(function(){ $._ = '(!!_s[_i]&&' + dqEscape($._) + '.indexOf(_s[_i])>=0)&&(++_i,true)' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||DOT($)&&(function(){ $._ = '(!!_s[_i])&&(++_i,true)' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||OPEN($)&&Expression($)&&CLOSE($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Identifier($){return (function(){var _b=_i;return (function(){var _m=_i;return (function(){var _b=_i;return IdentStart($)&&((function(){while(IdentCont($));})(),true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()&&($._=_s.slice(_m,_i),true)})()&&Spacing($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function IdentStart($){return (function(){var _b=_i;return (!!_s[_i]&&"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_".indexOf(_s[_i])>=0)&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function IdentCont($){return (function(){var _b=_i;return IdentStart($)||(_im=(_i>_im?_i:_im),_i=_b,false)||(!!_s[_i]&&"0123456789".indexOf(_s[_i])>=0)&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Variable($){var $;return (function(){var _b=_i;return (function(){var _b=_i;return (_s.substr(_i,3)==="$$.")&&(_i+=3,true)&&(function(){var _m=_i;return PikaVar($)&&($._=_s.slice(_m,_i),true)})()&&(function(){ $._ = '$.' + $._ ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||(_s.substr(_i,2)==="$$")&&(_i+=2,true)&&(function(){ $._ = '$._' ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||(function(){var _m=_i;return PikaVar($)&&($._=_s.slice(_m,_i),true)})()&&(function(){ $._ = '$' + $._ ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()&&Spacing($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Literal($){var $c={};return (function(){var _b=_i;return (function(){ $._ = '' ; return true})()&&(!!_s[_i]&&"'".indexOf(_s[_i])>=0)&&(++_i,true)&&((function(){while((function(){var _b=_i;return (function(){var _l=_i,_x=(!!_s[_i]&&"'".indexOf(_s[_i])>=0)&&(++_i,true);_i=_l;return !_x})()&&Char($c)&&(function(){ $._ += $c._ ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(!!_s[_i]&&"'".indexOf(_s[_i])>=0)&&(++_i,true)&&Spacing($)||(_im=(_i>_im?_i:_im),_i=_b,false)||(!!_s[_i]&&"\"".indexOf(_s[_i])>=0)&&(++_i,true)&&((function(){while((function(){var _b=_i;return (function(){var _l=_i,_x=(!!_s[_i]&&"\"".indexOf(_s[_i])>=0)&&(++_i,true);_i=_l;return !_x})()&&Char($c)&&(function(){ $._ += $c._ ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(!!_s[_i]&&"\"".indexOf(_s[_i])>=0)&&(++_i,true)&&Spacing($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Class($){var $r={};return (function(){var _b=_i;return (function(){ $._ = '' ; return true})()&&(_s[_i]==="[")&&(++_i,true)&&((function(){while((function(){var _b=_i;return (function(){var _l=_i,_x=(_s[_i]==="]")&&(++_i,true);_i=_l;return !_x})()&&Range($r)&&(function(){ $._ += $r._ ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(_s[_i]==="]")&&(++_i,true)&&Spacing($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Range($){var $f={},$t={};return (function(){var _b=_i;return Char($f)&&(_s[_i]==="-")&&(++_i,true)&&Char($t)&&(function(){ $._ = ''; for (var i = ($f._).charCodeAt(0), e = ($t._).charCodeAt(0); i <= e; ++i) $._ += String.fromCharCode(i); ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||Char($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Char($){var $x;return (function(){var _b=_i;return (_s[_i]==="\\")&&(++_i,true)&&(function(){var _m=_i;return (!!_s[_i]&&"nrt'\"[]\\".indexOf(_s[_i])>=0)&&(++_i,true)&&($x=_s.slice(_m,_i),true)})()&&(function(){ $._ = "\n\r\t'\"[]\\"[("nrt'\"[]\\").indexOf($x)] ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||(_s[_i]==="\\")&&(++_i,true)&&(function(){var _m=_i;return (function(){var _b=_i;return (!!_s[_i]&&"0123".indexOf(_s[_i])>=0)&&(++_i,true)&&(!!_s[_i]&&"01234567".indexOf(_s[_i])>=0)&&(++_i,true)&&(!!_s[_i]&&"01234567".indexOf(_s[_i])>=0)&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()&&($x=_s.slice(_m,_i),true)})()&&(function(){ $._ = String.fromCharCode($x[0] * 64 + $x[1] * 8 + +$x[2]) ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||(_s[_i]==="\\")&&(++_i,true)&&(function(){var _m=_i;return (function(){var _b=_i;return (!!_s[_i]&&"01234567".indexOf(_s[_i])>=0)&&(++_i,true)&&(!!_s[_i]&&"01234567".indexOf(_s[_i])>=0)&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()&&($x=_s.slice(_m,_i),true)})()&&(function(){ $._ = String.fromCharCode($x[0] * 8 + +$x[1]) ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||(_s[_i]==="\\")&&(++_i,true)&&(function(){var _m=_i;return (function(){var _b=_i;return (!!_s[_i]&&"01234567".indexOf(_s[_i])>=0)&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()&&($x=_s.slice(_m,_i),true)})()&&(function(){ $._ = String.fromCharCode(+$x[0]) ; return true})()||(_im=(_i>_im?_i:_im),_i=_b,false)||(function(){var _l=_i,_x=(!!_s[_i]&&"\\\u0000\u0001\u0002\u0003\u0004\u0005\u0006\u0007\b\t\n\u000b\f\r\u000e\u000f\u0010\u0011\u0012\u0013\u0014\u0015\u0016\u0017\u0018\u0019\u001a\u001b\u001c\u001d\u001e\u001f".indexOf(_s[_i])>=0)&&(++_i,true);_i=_l;return !_x})()&&(function(){var _m=_i;return (!!_s[_i])&&(++_i,true)&&($._=_s.slice(_m,_i),true)})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Spacing($){return (function(){var _b=_i;return ((function(){while((function(){var _b=_i;return Space($)||(_im=(_i>_im?_i:_im),_i=_b,false)||Comment($)||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Comment($){return (function(){var _b=_i;return (_s[_i]==="#")&&(++_i,true)&&((function(){while((function(){var _b=_i;return (function(){var _l=_i,_x=EndOfLine($);_i=_l;return !_x})()&&(!!_s[_i])&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(function(){var _b=_i;return EndOfLine($)||(_im=(_i>_im?_i:_im),_i=_b,false)||EndOfFile($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function Space($){return (function(){var _b=_i;return (_s[_i]===" ")&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)||(_s[_i]==="\t")&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)||EndOfLine($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function EndOfLine($){return (function(){var _b=_i;return (_s.substr(_i,2)==="\r\n")&&(_i+=2,true)||(_im=(_i>_im?_i:_im),_i=_b,false)||(_s[_i]==="\n")&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)||(_s[_i]==="\r")&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function EndOfFile($){return (function(){var _b=_i;return (function(){var _l=_i,_x=(!!_s[_i])&&(++_i,true);_i=_l;return !_x})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function PikaVar($){return (function(){var _b=_i;return (!!_s[_i]&&"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_".indexOf(_s[_i])>=0)&&(++_i,true)&&((function(){while((function(){var _b=_i;return ((_s[_i]===".")&&(++_i,true),true)&&(!!_s[_i]&&"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ$_0123456789".indexOf(_s[_i])>=0)&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function PikaBlock($){return (function(){var _b=_i;return (_s[_i]==="{")&&(++_i,true)&&((function(){while((function(){var _b=_i;return (function(){var _l=_i,_x=(_s[_i]==="{")&&(++_i,true);_i=_l;return _x})()&&PikaBlock($)||(_im=(_i>_im?_i:_im),_i=_b,false)||(function(){var _l=_i,_x=(!!_s[_i]&&"\"'".indexOf(_s[_i])>=0)&&(++_i,true);_i=_l;return _x})()&&PikaString($)||(_im=(_i>_im?_i:_im),_i=_b,false)||(function(){var _l=_i,_x=(function(){var _b=_i;return (_s.substr(_i,2)==="/*")&&(_i+=2,true)||(_im=(_i>_im?_i:_im),_i=_b,false)||(_s.substr(_i,2)==="//")&&(_i+=2,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})();_i=_l;return _x})()&&PikaComment($)||(_im=(_i>_im?_i:_im),_i=_b,false)||(function(){var _l=_i,_x=(_s[_i]==="}")&&(++_i,true);_i=_l;return !_x})()&&(!!_s[_i])&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(_s[_i]==="}")&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function PikaString($){return (function(){var _b=_i;return (_s[_i]==="\"")&&(++_i,true)&&((function(){while((function(){var _b=_i;return (function(){var _b=_i;return (_s[_i]==="\\")&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)||(function(){var _l=_i,_x=(_s[_i]==="\"")&&(++_i,true);_i=_l;return !_x})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()&&(!!_s[_i])&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(_s[_i]==="\"")&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)||(_s[_i]==="'")&&(++_i,true)&&((function(){while((function(){var _b=_i;return (function(){var _b=_i;return (_s.substr(_i,2)==="''")&&(_i+=2,true)||(_im=(_i>_im?_i:_im),_i=_b,false)||(function(){var _l=_i,_x=(_s[_i]==="'")&&(++_i,true);_i=_l;return !_x})()&&(!!_s[_i])&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(_s[_i]==="'")&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function PikaComment($){return (function(){var _b=_i;return (_s.substr(_i,2)==="/*")&&(_i+=2,true)&&((function(){while((function(){var _b=_i;return (function(){var _l=_i,_x=(_s.substr(_i,2)==="*/")&&(_i+=2,true);_i=_l;return !_x})()&&(!!_s[_i])&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(_s.substr(_i,2)==="*/")&&(_i+=2,true)||(_im=(_i>_im?_i:_im),_i=_b,false)||(_s.substr(_i,2)==="//")&&(_i+=2,true)&&((function(){while((function(){var _b=_i;return (function(){var _l=_i,_x=EndOfLine($);_i=_l;return !_x})()&&(!!_s[_i])&&(++_i,true)||(_im=(_i>_im?_i:_im),_i=_b,false)})());})(),true)&&(function(){var _b=_i;return EndOfLine($)||(_im=(_i>_im?_i:_im),_i=_b,false)||EndOfFile($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function LEFTARROW($){return (function(){var _b=_i;return (_s.substr(_i,2)==="<-")&&(_i+=2,true)&&Spacing($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function SLASH($){return (function(){var _b=_i;return (_s[_i]==="/")&&(++_i,true)&&Spacing($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function AND($){return (function(){var _b=_i;return (_s[_i]==="&")&&(++_i,true)&&Spacing($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function NOT($){return (function(){var _b=_i;return (_s[_i]==="!")&&(++_i,true)&&Spacing($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function QUESTION($){return (function(){var _b=_i;return (_s[_i]==="?")&&(++_i,true)&&Spacing($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function STAR($){return (function(){var _b=_i;return (_s[_i]==="*")&&(++_i,true)&&Spacing($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function PLUS($){return (function(){var _b=_i;return (_s[_i]==="+")&&(++_i,true)&&Spacing($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function OPEN($){return (function(){var _b=_i;return (_s[_i]==="(")&&(++_i,true)&&Spacing($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function CLOSE($){return (function(){var _b=_i;return (_s[_i]===")")&&(++_i,true)&&Spacing($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function DOT($){return (function(){var _b=_i;return (_s[_i]===".")&&(++_i,true)&&Spacing($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function COLON($){return (function(){var _b=_i;return (_s[_i]===":")&&(++_i,true)&&Spacing($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
function EQUALS($){return (function(){var _b=_i;return (_s[_i]==="=")&&(++_i,true)&&Spacing($)||(_im=(_i>_im?_i:_im),_i=_b,false)})()};
var _i=0,_im=0,_o={_:void 0},_b=root(_o);
return [_b,_o._,(_b?_i:_im)];
});
if (typeof module !== 'undefined' && module.exports) {
	module.exports = compileJSPEG;
	module.exports.compileJSPEG = compileJSPEG;
	module.exports.default = compileJSPEG;
}
