#!/usr/bin/env bash
#
# Generate + compile the per-instruction interpreter microbenchmarks.
#
# Each microbench is a tight loop whose body is K copies of a SINGLE target instruction,
# chained through `acc` so nothing is dead-code eliminated. Loop overhead is amortised by
# the unroll, so wall time is dominated by the target opcode. All operands are variables,
# so the run-time opcode form (_VVV / _VV_ / _VVC) is exercised - the same paths the UB
# helpers route through - never the compile-time constant folder.
#
# `xor` is the CONTROL: bitwise XOR is explicitly untouched by the UB fix, so its timing
# must NOT move across the change. It validates that the harness itself is stable.
#
# Sources are written to tests/bench/sources/ and compiled to tests/bench/golden/.
# Both are committed; bench.sh runs the golden .gazl directly (no compiler needed at run time).
# Re-run this script after changing the parameters below or the Impala compiler.
#
set -e -o pipefail -u
cd "$(dirname "$0")/.."

UNROLL=32            # target ops per loop iteration
ITERS=4000000        # loop iterations  ->  UNROLL*ITERS = 128M target ops per bench
SEED=0x4d2           # fixed compile seed so the golden .gazl is reproducible

SRC=tests/bench/sources
GOLD=tests/bench/golden
mkdir -p "$SRC" "$GOLD"

if [ ! -f output/impala.nuxjs.js ] || [ ! -x output/NuXJS ]; then
	echo "error: output/impala.nuxjs.js or output/NuXJS missing -- run build.sh first" >&2
	exit 1
fi

# name  body-statement                 mnemonic-emitted (for verification)
ops=(
	"add:acc = acc + a;:ADDi"
	"sub:acc = acc - a;:SUBi"
	"mul:acc = acc * a;:MULi"
	"div:acc = acc / b;:DIVi"
	"mod:acc = acc % b;:MODi"
	"shl:acc = acc << s;:SHLi"
	"shr:acc = acc >> s;:SHRi"
	"shru:acc = acc >>> s;:SHRu"
	"abs:acc = abs(acc);:ABSi"
	"ftoi:acc = ftoi(f);:fTOi"
	"xor:acc = acc ^ a;:XORi"
)

for entry in "${ops[@]}"; do
	name=${entry%%:*}
	rest=${entry#*:}
	body=${rest%:*}
	mnem=${rest##*:}
	impala="$SRC/op_$name.impala"
	gazl="$GOLD/op_$name.gazl"

	{
		echo "// GENERATED by tools/genbench.sh -- do not edit by hand."
		echo "// Microbenchmark: $UNROLL x ($body) per iteration, $ITERS iterations."
		echo "extern native printInt;"
		echo ""
		echo "function main()"
		echo "locals int i, int acc, int a, int b, int s, float f"
		echo "{"
		echo "	a = 123456789; b = 3; s = 1; f = 123.5; acc = a;"
		echo "	for (i = 0 to $ITERS) {"
		for ((k = 0; k < UNROLL; ++k)); do echo "		$body"; done
		echo "	}"
		echo "	printInt(acc);"
		echo "}"
	} > "$impala"

	./output/NuXJS output/impala.nuxjs.js "$impala" "$gazl" "$SEED" "op_$name.impala" >/dev/null 2>&1

	count=$(grep -c "	$mnem " "$gazl" || true)
	if [ "$count" -lt "$UNROLL" ]; then
		echo "FAIL  op_$name: expected >= $UNROLL '$mnem' in loop, found $count" >&2
		exit 1
	fi
	printf 'ok    op_%-6s %s x%d  (%d %s emitted)\n' "$name" "$mnem" "$UNROLL" "$count" "$mnem"
done

echo "Generated ${#ops[@]} microbenchmarks in $GOLD"
